// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: param_v.proto

package cn.autolabor.plugin.gazebo.msgs;

public final class ProtoParamV {
  private ProtoParamV() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Param_VOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gazebo.msgs.Param_V)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param> 
        getParamList();
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param getParam(int index);
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    int getParamCount();
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    java.util.List<? extends cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder> 
        getParamOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder getParamOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gazebo.msgs.Param_V}
   */
  public static final class Param_V extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:gazebo.msgs.Param_V)
      Param_VOrBuilder {
    // Use Param_V.newBuilder() to construct.
    private Param_V(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Param_V(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Param_V defaultInstance;
    public static Param_V getDefaultInstance() {
      return defaultInstance;
    }

    public Param_V getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Param_V(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                param_ = new java.util.ArrayList<cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param>();
                mutable_bitField0_ |= 0x00000001;
              }
              param_.add(input.readMessage(cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          param_ = java.util.Collections.unmodifiableList(param_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.autolabor.plugin.gazebo.msgs.ProtoParamV.internal_static_gazebo_msgs_Param_V_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.autolabor.plugin.gazebo.msgs.ProtoParamV.internal_static_gazebo_msgs_Param_V_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V.class, cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V.Builder.class);
    }

    public static com.google.protobuf.Parser<Param_V> PARSER =
        new com.google.protobuf.AbstractParser<Param_V>() {
      public Param_V parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Param_V(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Param_V> getParserForType() {
      return PARSER;
    }

    public static final int PARAM_FIELD_NUMBER = 1;
    private java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param> param_;
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    public java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param> getParamList() {
      return param_;
    }
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    public java.util.List<? extends cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder> 
        getParamOrBuilderList() {
      return param_;
    }
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    public int getParamCount() {
      return param_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    public cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param getParam(int index) {
      return param_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.Param param = 1;</code>
     */
    public cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder getParamOrBuilder(
        int index) {
      return param_.get(index);
    }

    private void initFields() {
      param_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getParamCount(); i++) {
        if (!getParam(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < param_.size(); i++) {
        output.writeMessage(1, param_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < param_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, param_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.Param_V}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gazebo.msgs.Param_V)
        cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_VOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoParamV.internal_static_gazebo_msgs_Param_V_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoParamV.internal_static_gazebo_msgs_Param_V_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V.class, cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V.Builder.class);
      }

      // Construct using cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParamFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (paramBuilder_ == null) {
          param_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          paramBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoParamV.internal_static_gazebo_msgs_Param_V_descriptor;
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V getDefaultInstanceForType() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V.getDefaultInstance();
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V build() {
        cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V buildPartial() {
        cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V result = new cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V(this);
        int from_bitField0_ = bitField0_;
        if (paramBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            param_ = java.util.Collections.unmodifiableList(param_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.param_ = param_;
        } else {
          result.param_ = paramBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V) {
          return mergeFrom((cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V other) {
        if (other == cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V.getDefaultInstance()) return this;
        if (paramBuilder_ == null) {
          if (!other.param_.isEmpty()) {
            if (param_.isEmpty()) {
              param_ = other.param_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureParamIsMutable();
              param_.addAll(other.param_);
            }
            onChanged();
          }
        } else {
          if (!other.param_.isEmpty()) {
            if (paramBuilder_.isEmpty()) {
              paramBuilder_.dispose();
              paramBuilder_ = null;
              param_ = other.param_;
              bitField0_ = (bitField0_ & ~0x00000001);
              paramBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParamFieldBuilder() : null;
            } else {
              paramBuilder_.addAllMessages(other.param_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getParamCount(); i++) {
          if (!getParam(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.autolabor.plugin.gazebo.msgs.ProtoParamV.Param_V) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param> param_ =
        java.util.Collections.emptyList();
      private void ensureParamIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          param_ = new java.util.ArrayList<cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param>(param_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param, cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder> paramBuilder_;

      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param> getParamList() {
        if (paramBuilder_ == null) {
          return java.util.Collections.unmodifiableList(param_);
        } else {
          return paramBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public int getParamCount() {
        if (paramBuilder_ == null) {
          return param_.size();
        } else {
          return paramBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param getParam(int index) {
        if (paramBuilder_ == null) {
          return param_.get(index);
        } else {
          return paramBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder setParam(
          int index, cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param value) {
        if (paramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamIsMutable();
          param_.set(index, value);
          onChanged();
        } else {
          paramBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder setParam(
          int index, cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder builderForValue) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          param_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder addParam(cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param value) {
        if (paramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamIsMutable();
          param_.add(value);
          onChanged();
        } else {
          paramBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder addParam(
          int index, cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param value) {
        if (paramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamIsMutable();
          param_.add(index, value);
          onChanged();
        } else {
          paramBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder addParam(
          cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder builderForValue) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          param_.add(builderForValue.build());
          onChanged();
        } else {
          paramBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder addParam(
          int index, cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder builderForValue) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          param_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder addAllParam(
          java.lang.Iterable<? extends cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param> values) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, param_);
          onChanged();
        } else {
          paramBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder clearParam() {
        if (paramBuilder_ == null) {
          param_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          paramBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public Builder removeParam(int index) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          param_.remove(index);
          onChanged();
        } else {
          paramBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder getParamBuilder(
          int index) {
        return getParamFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder getParamOrBuilder(
          int index) {
        if (paramBuilder_ == null) {
          return param_.get(index);  } else {
          return paramBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public java.util.List<? extends cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder> 
           getParamOrBuilderList() {
        if (paramBuilder_ != null) {
          return paramBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(param_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder addParamBuilder() {
        return getParamFieldBuilder().addBuilder(
            cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder addParamBuilder(
          int index) {
        return getParamFieldBuilder().addBuilder(
            index, cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Param param = 1;</code>
       */
      public java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder> 
           getParamBuilderList() {
        return getParamFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param, cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder> 
          getParamFieldBuilder() {
        if (paramBuilder_ == null) {
          paramBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param, cn.autolabor.plugin.gazebo.msgs.ProtoParam.Param.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoParam.ParamOrBuilder>(
                  param_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          param_ = null;
        }
        return paramBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.Param_V)
    }

    static {
      defaultInstance = new Param_V(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.Param_V)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_Param_V_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_Param_V_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rparam_v.proto\022\013gazebo.msgs\032\013param.prot" +
      "o\",\n\007Param_V\022!\n\005param\030\001 \003(\0132\022.gazebo.msg" +
      "s.ParamB.\n\037cn.autolabor.plugin.gazebo.ms" +
      "gsB\013ProtoParamV"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.autolabor.plugin.gazebo.msgs.ProtoParam.getDescriptor(),
        }, assigner);
    internal_static_gazebo_msgs_Param_V_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gazebo_msgs_Param_V_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gazebo_msgs_Param_V_descriptor,
        new java.lang.String[] { "Param", });
    cn.autolabor.plugin.gazebo.msgs.ProtoParam.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
