// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diagnostics.proto

package cn.autolabor.plugin.gazebo.msgs;

public final class ProtoDiagnostics {
  private ProtoDiagnostics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DiagnosticsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gazebo.msgs.Diagnostics)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime> 
        getTimeList();
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime getTime(int index);
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    int getTimeCount();
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    java.util.List<? extends cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder> 
        getTimeOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder getTimeOrBuilder(
        int index);

    /**
     * <code>required .gazebo.msgs.Time real_time = 2;</code>
     */
    boolean hasRealTime();
    /**
     * <code>required .gazebo.msgs.Time real_time = 2;</code>
     */
    cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getRealTime();
    /**
     * <code>required .gazebo.msgs.Time real_time = 2;</code>
     */
    cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getRealTimeOrBuilder();

    /**
     * <code>required .gazebo.msgs.Time sim_time = 3;</code>
     */
    boolean hasSimTime();
    /**
     * <code>required .gazebo.msgs.Time sim_time = 3;</code>
     */
    cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getSimTime();
    /**
     * <code>required .gazebo.msgs.Time sim_time = 3;</code>
     */
    cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getSimTimeOrBuilder();

    /**
     * <code>required double real_time_factor = 4;</code>
     */
    boolean hasRealTimeFactor();
    /**
     * <code>required double real_time_factor = 4;</code>
     */
    double getRealTimeFactor();
  }
  /**
   * Protobuf type {@code gazebo.msgs.Diagnostics}
   */
  public static final class Diagnostics extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:gazebo.msgs.Diagnostics)
      DiagnosticsOrBuilder {
    // Use Diagnostics.newBuilder() to construct.
    private Diagnostics(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Diagnostics(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Diagnostics defaultInstance;
    public static Diagnostics getDefaultInstance() {
      return defaultInstance;
    }

    public Diagnostics getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Diagnostics(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                time_ = new java.util.ArrayList<cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime>();
                mutable_bitField0_ |= 0x00000001;
              }
              time_.add(input.readMessage(cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = realTime_.toBuilder();
              }
              realTime_ = input.readMessage(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(realTime_);
                realTime_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 26: {
              cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = simTime_.toBuilder();
              }
              simTime_ = input.readMessage(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simTime_);
                simTime_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 33: {
              bitField0_ |= 0x00000004;
              realTimeFactor_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          time_ = java.util.Collections.unmodifiableList(time_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.class, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.Builder.class);
    }

    public static com.google.protobuf.Parser<Diagnostics> PARSER =
        new com.google.protobuf.AbstractParser<Diagnostics>() {
      public Diagnostics parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Diagnostics(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Diagnostics> getParserForType() {
      return PARSER;
    }

    public interface DiagTimeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gazebo.msgs.Diagnostics.DiagTime)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>required .gazebo.msgs.Time elapsed = 2;</code>
       */
      boolean hasElapsed();
      /**
       * <code>required .gazebo.msgs.Time elapsed = 2;</code>
       */
      cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getElapsed();
      /**
       * <code>required .gazebo.msgs.Time elapsed = 2;</code>
       */
      cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getElapsedOrBuilder();

      /**
       * <code>required .gazebo.msgs.Time wall = 3;</code>
       */
      boolean hasWall();
      /**
       * <code>required .gazebo.msgs.Time wall = 3;</code>
       */
      cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getWall();
      /**
       * <code>required .gazebo.msgs.Time wall = 3;</code>
       */
      cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getWallOrBuilder();
    }
    /**
     * Protobuf type {@code gazebo.msgs.Diagnostics.DiagTime}
     */
    public static final class DiagTime extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:gazebo.msgs.Diagnostics.DiagTime)
        DiagTimeOrBuilder {
      // Use DiagTime.newBuilder() to construct.
      private DiagTime(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private DiagTime(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final DiagTime defaultInstance;
      public static DiagTime getDefaultInstance() {
        return defaultInstance;
      }

      public DiagTime getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private DiagTime(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                name_ = bs;
                break;
              }
              case 18: {
                cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = elapsed_.toBuilder();
                }
                elapsed_ = input.readMessage(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(elapsed_);
                  elapsed_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
              case 26: {
                cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder subBuilder = null;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                  subBuilder = wall_.toBuilder();
                }
                wall_ = input.readMessage(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(wall_);
                  wall_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000004;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_DiagTime_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_DiagTime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.class, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder.class);
      }

      public static com.google.protobuf.Parser<DiagTime> PARSER =
          new com.google.protobuf.AbstractParser<DiagTime>() {
        public DiagTime parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DiagTime(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<DiagTime> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ELAPSED_FIELD_NUMBER = 2;
      private cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time elapsed_;
      /**
       * <code>required .gazebo.msgs.Time elapsed = 2;</code>
       */
      public boolean hasElapsed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .gazebo.msgs.Time elapsed = 2;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getElapsed() {
        return elapsed_;
      }
      /**
       * <code>required .gazebo.msgs.Time elapsed = 2;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getElapsedOrBuilder() {
        return elapsed_;
      }

      public static final int WALL_FIELD_NUMBER = 3;
      private cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time wall_;
      /**
       * <code>required .gazebo.msgs.Time wall = 3;</code>
       */
      public boolean hasWall() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .gazebo.msgs.Time wall = 3;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getWall() {
        return wall_;
      }
      /**
       * <code>required .gazebo.msgs.Time wall = 3;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getWallOrBuilder() {
        return wall_;
      }

      private void initFields() {
        name_ = "";
        elapsed_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
        wall_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasElapsed()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWall()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getElapsed().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getWall().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, elapsed_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeMessage(3, wall_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, elapsed_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, wall_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gazebo.msgs.Diagnostics.DiagTime}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gazebo.msgs.Diagnostics.DiagTime)
          cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_DiagTime_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_DiagTime_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.class, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder.class);
        }

        // Construct using cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getElapsedFieldBuilder();
            getWallFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          if (elapsedBuilder_ == null) {
            elapsed_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
          } else {
            elapsedBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          if (wallBuilder_ == null) {
            wall_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
          } else {
            wallBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_DiagTime_descriptor;
        }

        public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime getDefaultInstanceForType() {
          return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.getDefaultInstance();
        }

        public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime build() {
          cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime buildPartial() {
          cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime result = new cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (elapsedBuilder_ == null) {
            result.elapsed_ = elapsed_;
          } else {
            result.elapsed_ = elapsedBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          if (wallBuilder_ == null) {
            result.wall_ = wall_;
          } else {
            result.wall_ = wallBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime) {
            return mergeFrom((cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime other) {
          if (other == cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasElapsed()) {
            mergeElapsed(other.getElapsed());
          }
          if (other.hasWall()) {
            mergeWall(other.getWall());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasElapsed()) {
            
            return false;
          }
          if (!hasWall()) {
            
            return false;
          }
          if (!getElapsed().isInitialized()) {
            
            return false;
          }
          if (!getWall().isInitialized()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        private cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time elapsed_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder> elapsedBuilder_;
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        public boolean hasElapsed() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getElapsed() {
          if (elapsedBuilder_ == null) {
            return elapsed_;
          } else {
            return elapsedBuilder_.getMessage();
          }
        }
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        public Builder setElapsed(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time value) {
          if (elapsedBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            elapsed_ = value;
            onChanged();
          } else {
            elapsedBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        public Builder setElapsed(
            cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder builderForValue) {
          if (elapsedBuilder_ == null) {
            elapsed_ = builderForValue.build();
            onChanged();
          } else {
            elapsedBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        public Builder mergeElapsed(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time value) {
          if (elapsedBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                elapsed_ != cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance()) {
              elapsed_ =
                cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.newBuilder(elapsed_).mergeFrom(value).buildPartial();
            } else {
              elapsed_ = value;
            }
            onChanged();
          } else {
            elapsedBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        public Builder clearElapsed() {
          if (elapsedBuilder_ == null) {
            elapsed_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
            onChanged();
          } else {
            elapsedBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder getElapsedBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getElapsedFieldBuilder().getBuilder();
        }
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        public cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getElapsedOrBuilder() {
          if (elapsedBuilder_ != null) {
            return elapsedBuilder_.getMessageOrBuilder();
          } else {
            return elapsed_;
          }
        }
        /**
         * <code>required .gazebo.msgs.Time elapsed = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder> 
            getElapsedFieldBuilder() {
          if (elapsedBuilder_ == null) {
            elapsedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder>(
                    getElapsed(),
                    getParentForChildren(),
                    isClean());
            elapsed_ = null;
          }
          return elapsedBuilder_;
        }

        private cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time wall_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder> wallBuilder_;
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        public boolean hasWall() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getWall() {
          if (wallBuilder_ == null) {
            return wall_;
          } else {
            return wallBuilder_.getMessage();
          }
        }
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        public Builder setWall(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time value) {
          if (wallBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            wall_ = value;
            onChanged();
          } else {
            wallBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        public Builder setWall(
            cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder builderForValue) {
          if (wallBuilder_ == null) {
            wall_ = builderForValue.build();
            onChanged();
          } else {
            wallBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        public Builder mergeWall(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time value) {
          if (wallBuilder_ == null) {
            if (((bitField0_ & 0x00000004) == 0x00000004) &&
                wall_ != cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance()) {
              wall_ =
                cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.newBuilder(wall_).mergeFrom(value).buildPartial();
            } else {
              wall_ = value;
            }
            onChanged();
          } else {
            wallBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        public Builder clearWall() {
          if (wallBuilder_ == null) {
            wall_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
            onChanged();
          } else {
            wallBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder getWallBuilder() {
          bitField0_ |= 0x00000004;
          onChanged();
          return getWallFieldBuilder().getBuilder();
        }
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        public cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getWallOrBuilder() {
          if (wallBuilder_ != null) {
            return wallBuilder_.getMessageOrBuilder();
          } else {
            return wall_;
          }
        }
        /**
         * <code>required .gazebo.msgs.Time wall = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder> 
            getWallFieldBuilder() {
          if (wallBuilder_ == null) {
            wallBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder>(
                    getWall(),
                    getParentForChildren(),
                    isClean());
            wall_ = null;
          }
          return wallBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:gazebo.msgs.Diagnostics.DiagTime)
      }

      static {
        defaultInstance = new DiagTime(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:gazebo.msgs.Diagnostics.DiagTime)
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime> time_;
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    public java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime> getTimeList() {
      return time_;
    }
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    public java.util.List<? extends cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder> 
        getTimeOrBuilderList() {
      return time_;
    }
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    public int getTimeCount() {
      return time_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime getTime(int index) {
      return time_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
     */
    public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder getTimeOrBuilder(
        int index) {
      return time_.get(index);
    }

    public static final int REAL_TIME_FIELD_NUMBER = 2;
    private cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time realTime_;
    /**
     * <code>required .gazebo.msgs.Time real_time = 2;</code>
     */
    public boolean hasRealTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gazebo.msgs.Time real_time = 2;</code>
     */
    public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getRealTime() {
      return realTime_;
    }
    /**
     * <code>required .gazebo.msgs.Time real_time = 2;</code>
     */
    public cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getRealTimeOrBuilder() {
      return realTime_;
    }

    public static final int SIM_TIME_FIELD_NUMBER = 3;
    private cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time simTime_;
    /**
     * <code>required .gazebo.msgs.Time sim_time = 3;</code>
     */
    public boolean hasSimTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .gazebo.msgs.Time sim_time = 3;</code>
     */
    public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getSimTime() {
      return simTime_;
    }
    /**
     * <code>required .gazebo.msgs.Time sim_time = 3;</code>
     */
    public cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getSimTimeOrBuilder() {
      return simTime_;
    }

    public static final int REAL_TIME_FACTOR_FIELD_NUMBER = 4;
    private double realTimeFactor_;
    /**
     * <code>required double real_time_factor = 4;</code>
     */
    public boolean hasRealTimeFactor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double real_time_factor = 4;</code>
     */
    public double getRealTimeFactor() {
      return realTimeFactor_;
    }

    private void initFields() {
      time_ = java.util.Collections.emptyList();
      realTime_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
      simTime_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
      realTimeFactor_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRealTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSimTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRealTimeFactor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTimeCount(); i++) {
        if (!getTime(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getRealTime().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSimTime().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < time_.size(); i++) {
        output.writeMessage(1, time_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, realTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, simTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(4, realTimeFactor_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < time_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, time_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, realTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, simTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, realTimeFactor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.Diagnostics}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gazebo.msgs.Diagnostics)
        cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.DiagnosticsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.class, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.Builder.class);
      }

      // Construct using cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTimeFieldBuilder();
          getRealTimeFieldBuilder();
          getSimTimeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (timeBuilder_ == null) {
          time_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          timeBuilder_.clear();
        }
        if (realTimeBuilder_ == null) {
          realTime_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
        } else {
          realTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (simTimeBuilder_ == null) {
          simTime_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
        } else {
          simTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        realTimeFactor_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.internal_static_gazebo_msgs_Diagnostics_descriptor;
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics getDefaultInstanceForType() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.getDefaultInstance();
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics build() {
        cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics buildPartial() {
        cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics result = new cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            time_ = java.util.Collections.unmodifiableList(time_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (realTimeBuilder_ == null) {
          result.realTime_ = realTime_;
        } else {
          result.realTime_ = realTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (simTimeBuilder_ == null) {
          result.simTime_ = simTime_;
        } else {
          result.simTime_ = simTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.realTimeFactor_ = realTimeFactor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics) {
          return mergeFrom((cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics other) {
        if (other == cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.getDefaultInstance()) return this;
        if (timeBuilder_ == null) {
          if (!other.time_.isEmpty()) {
            if (time_.isEmpty()) {
              time_ = other.time_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTimeIsMutable();
              time_.addAll(other.time_);
            }
            onChanged();
          }
        } else {
          if (!other.time_.isEmpty()) {
            if (timeBuilder_.isEmpty()) {
              timeBuilder_.dispose();
              timeBuilder_ = null;
              time_ = other.time_;
              bitField0_ = (bitField0_ & ~0x00000001);
              timeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTimeFieldBuilder() : null;
            } else {
              timeBuilder_.addAllMessages(other.time_);
            }
          }
        }
        if (other.hasRealTime()) {
          mergeRealTime(other.getRealTime());
        }
        if (other.hasSimTime()) {
          mergeSimTime(other.getSimTime());
        }
        if (other.hasRealTimeFactor()) {
          setRealTimeFactor(other.getRealTimeFactor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRealTime()) {
          
          return false;
        }
        if (!hasSimTime()) {
          
          return false;
        }
        if (!hasRealTimeFactor()) {
          
          return false;
        }
        for (int i = 0; i < getTimeCount(); i++) {
          if (!getTime(i).isInitialized()) {
            
            return false;
          }
        }
        if (!getRealTime().isInitialized()) {
          
          return false;
        }
        if (!getSimTime().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime> time_ =
        java.util.Collections.emptyList();
      private void ensureTimeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          time_ = new java.util.ArrayList<cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime>(time_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder> timeBuilder_;

      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime> getTimeList() {
        if (timeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(time_);
        } else {
          return timeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public int getTimeCount() {
        if (timeBuilder_ == null) {
          return time_.size();
        } else {
          return timeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime getTime(int index) {
        if (timeBuilder_ == null) {
          return time_.get(index);
        } else {
          return timeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder setTime(
          int index, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.set(index, value);
          onChanged();
        } else {
          timeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder setTime(
          int index, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.set(index, builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder addTime(cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.add(value);
          onChanged();
        } else {
          timeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder addTime(
          int index, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.add(index, value);
          onChanged();
        } else {
          timeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder addTime(
          cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.add(builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder addTime(
          int index, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.add(index, builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder addAllTime(
          java.lang.Iterable<? extends cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime> values) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, time_);
          onChanged();
        } else {
          timeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          timeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public Builder removeTime(int index) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.remove(index);
          onChanged();
        } else {
          timeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder getTimeBuilder(
          int index) {
        return getTimeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder getTimeOrBuilder(
          int index) {
        if (timeBuilder_ == null) {
          return time_.get(index);  } else {
          return timeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public java.util.List<? extends cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder> 
           getTimeOrBuilderList() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(time_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder addTimeBuilder() {
        return getTimeFieldBuilder().addBuilder(
            cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder addTimeBuilder(
          int index) {
        return getTimeFieldBuilder().addBuilder(
            index, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Diagnostics.DiagTime time = 1;</code>
       */
      public java.util.List<cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder> 
           getTimeBuilderList() {
        return getTimeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTime.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoDiagnostics.Diagnostics.DiagTimeOrBuilder>(
                  time_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      private cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time realTime_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder> realTimeBuilder_;
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      public boolean hasRealTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getRealTime() {
        if (realTimeBuilder_ == null) {
          return realTime_;
        } else {
          return realTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      public Builder setRealTime(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time value) {
        if (realTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          realTime_ = value;
          onChanged();
        } else {
          realTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      public Builder setRealTime(
          cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder builderForValue) {
        if (realTimeBuilder_ == null) {
          realTime_ = builderForValue.build();
          onChanged();
        } else {
          realTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      public Builder mergeRealTime(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time value) {
        if (realTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              realTime_ != cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance()) {
            realTime_ =
              cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.newBuilder(realTime_).mergeFrom(value).buildPartial();
          } else {
            realTime_ = value;
          }
          onChanged();
        } else {
          realTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      public Builder clearRealTime() {
        if (realTimeBuilder_ == null) {
          realTime_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
          onChanged();
        } else {
          realTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder getRealTimeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRealTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getRealTimeOrBuilder() {
        if (realTimeBuilder_ != null) {
          return realTimeBuilder_.getMessageOrBuilder();
        } else {
          return realTime_;
        }
      }
      /**
       * <code>required .gazebo.msgs.Time real_time = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder> 
          getRealTimeFieldBuilder() {
        if (realTimeBuilder_ == null) {
          realTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder>(
                  getRealTime(),
                  getParentForChildren(),
                  isClean());
          realTime_ = null;
        }
        return realTimeBuilder_;
      }

      private cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time simTime_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder> simTimeBuilder_;
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      public boolean hasSimTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time getSimTime() {
        if (simTimeBuilder_ == null) {
          return simTime_;
        } else {
          return simTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      public Builder setSimTime(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time value) {
        if (simTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simTime_ = value;
          onChanged();
        } else {
          simTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      public Builder setSimTime(
          cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder builderForValue) {
        if (simTimeBuilder_ == null) {
          simTime_ = builderForValue.build();
          onChanged();
        } else {
          simTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      public Builder mergeSimTime(cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time value) {
        if (simTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              simTime_ != cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance()) {
            simTime_ =
              cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.newBuilder(simTime_).mergeFrom(value).buildPartial();
          } else {
            simTime_ = value;
          }
          onChanged();
        } else {
          simTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      public Builder clearSimTime() {
        if (simTimeBuilder_ == null) {
          simTime_ = cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.getDefaultInstance();
          onChanged();
        } else {
          simTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder getSimTimeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSimTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      public cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder getSimTimeOrBuilder() {
        if (simTimeBuilder_ != null) {
          return simTimeBuilder_.getMessageOrBuilder();
        } else {
          return simTime_;
        }
      }
      /**
       * <code>required .gazebo.msgs.Time sim_time = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder> 
          getSimTimeFieldBuilder() {
        if (simTimeBuilder_ == null) {
          simTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.msgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.msgs.ProtoTime.TimeOrBuilder>(
                  getSimTime(),
                  getParentForChildren(),
                  isClean());
          simTime_ = null;
        }
        return simTimeBuilder_;
      }

      private double realTimeFactor_ ;
      /**
       * <code>required double real_time_factor = 4;</code>
       */
      public boolean hasRealTimeFactor() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double real_time_factor = 4;</code>
       */
      public double getRealTimeFactor() {
        return realTimeFactor_;
      }
      /**
       * <code>required double real_time_factor = 4;</code>
       */
      public Builder setRealTimeFactor(double value) {
        bitField0_ |= 0x00000008;
        realTimeFactor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double real_time_factor = 4;</code>
       */
      public Builder clearRealTimeFactor() {
        bitField0_ = (bitField0_ & ~0x00000008);
        realTimeFactor_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.Diagnostics)
    }

    static {
      defaultInstance = new Diagnostics(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.Diagnostics)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_Diagnostics_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_Diagnostics_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_Diagnostics_DiagTime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_Diagnostics_DiagTime_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021diagnostics.proto\022\013gazebo.msgs\032\ntime.p" +
      "roto\"\202\002\n\013Diagnostics\022/\n\004time\030\001 \003(\0132!.gaz" +
      "ebo.msgs.Diagnostics.DiagTime\022$\n\treal_ti" +
      "me\030\002 \002(\0132\021.gazebo.msgs.Time\022#\n\010sim_time\030" +
      "\003 \002(\0132\021.gazebo.msgs.Time\022\030\n\020real_time_fa" +
      "ctor\030\004 \002(\001\032]\n\010DiagTime\022\014\n\004name\030\001 \002(\t\022\"\n\007" +
      "elapsed\030\002 \002(\0132\021.gazebo.msgs.Time\022\037\n\004wall" +
      "\030\003 \002(\0132\021.gazebo.msgs.TimeB3\n\037cn.autolabo" +
      "r.plugin.gazebo.msgsB\020ProtoDiagnostics"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.autolabor.plugin.gazebo.msgs.ProtoTime.getDescriptor(),
        }, assigner);
    internal_static_gazebo_msgs_Diagnostics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gazebo_msgs_Diagnostics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gazebo_msgs_Diagnostics_descriptor,
        new java.lang.String[] { "Time", "RealTime", "SimTime", "RealTimeFactor", });
    internal_static_gazebo_msgs_Diagnostics_DiagTime_descriptor =
      internal_static_gazebo_msgs_Diagnostics_descriptor.getNestedTypes().get(0);
    internal_static_gazebo_msgs_Diagnostics_DiagTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gazebo_msgs_Diagnostics_DiagTime_descriptor,
        new java.lang.String[] { "Name", "Elapsed", "Wall", });
    cn.autolabor.plugin.gazebo.msgs.ProtoTime.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
