// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rest_post.proto

package cn.autolabor.plugin.gazebo.msgs;

public final class ProtoRestPost {
  private ProtoRestPost() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RestPostOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gazebo.msgs.RestPost)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 id = 1;</code>
     *
     * <pre>
     *&#47; &#92;brief ID of this request message
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 1;</code>
     *
     * <pre>
     *&#47; &#92;brief ID of this request message
     * </pre>
     */
    int getId();

    /**
     * <code>required string route = 2;</code>
     *
     * <pre>
     *&#47; &#92;brief Route to post to.
     * </pre>
     */
    boolean hasRoute();
    /**
     * <code>required string route = 2;</code>
     *
     * <pre>
     *&#47; &#92;brief Route to post to.
     * </pre>
     */
    java.lang.String getRoute();
    /**
     * <code>required string route = 2;</code>
     *
     * <pre>
     *&#47; &#92;brief Route to post to.
     * </pre>
     */
    com.google.protobuf.ByteString
        getRouteBytes();

    /**
     * <code>required string json = 3;</code>
     *
     * <pre>
     *&#47; &#92;brief Data to post in JSON format
     * </pre>
     */
    boolean hasJson();
    /**
     * <code>required string json = 3;</code>
     *
     * <pre>
     *&#47; &#92;brief Data to post in JSON format
     * </pre>
     */
    java.lang.String getJson();
    /**
     * <code>required string json = 3;</code>
     *
     * <pre>
     *&#47; &#92;brief Data to post in JSON format
     * </pre>
     */
    com.google.protobuf.ByteString
        getJsonBytes();
  }
  /**
   * Protobuf type {@code gazebo.msgs.RestPost}
   */
  public static final class RestPost extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:gazebo.msgs.RestPost)
      RestPostOrBuilder {
    // Use RestPost.newBuilder() to construct.
    private RestPost(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RestPost(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RestPost defaultInstance;
    public static RestPost getDefaultInstance() {
      return defaultInstance;
    }

    public RestPost getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RestPost(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              route_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              json_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.internal_static_gazebo_msgs_RestPost_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.internal_static_gazebo_msgs_RestPost_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost.class, cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost.Builder.class);
    }

    public static com.google.protobuf.Parser<RestPost> PARSER =
        new com.google.protobuf.AbstractParser<RestPost>() {
      public RestPost parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RestPost(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RestPost> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     *
     * <pre>
     *&#47; &#92;brief ID of this request message
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     *
     * <pre>
     *&#47; &#92;brief ID of this request message
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int ROUTE_FIELD_NUMBER = 2;
    private java.lang.Object route_;
    /**
     * <code>required string route = 2;</code>
     *
     * <pre>
     *&#47; &#92;brief Route to post to.
     * </pre>
     */
    public boolean hasRoute() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string route = 2;</code>
     *
     * <pre>
     *&#47; &#92;brief Route to post to.
     * </pre>
     */
    public java.lang.String getRoute() {
      java.lang.Object ref = route_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          route_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string route = 2;</code>
     *
     * <pre>
     *&#47; &#92;brief Route to post to.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRouteBytes() {
      java.lang.Object ref = route_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        route_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JSON_FIELD_NUMBER = 3;
    private java.lang.Object json_;
    /**
     * <code>required string json = 3;</code>
     *
     * <pre>
     *&#47; &#92;brief Data to post in JSON format
     * </pre>
     */
    public boolean hasJson() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string json = 3;</code>
     *
     * <pre>
     *&#47; &#92;brief Data to post in JSON format
     * </pre>
     */
    public java.lang.String getJson() {
      java.lang.Object ref = json_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          json_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string json = 3;</code>
     *
     * <pre>
     *&#47; &#92;brief Data to post in JSON format
     * </pre>
     */
    public com.google.protobuf.ByteString
        getJsonBytes() {
      java.lang.Object ref = json_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        json_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      route_ = "";
      json_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRoute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJson()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRouteBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getJsonBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRouteBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getJsonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.RestPost}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gazebo.msgs.RestPost)
        cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.internal_static_gazebo_msgs_RestPost_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.internal_static_gazebo_msgs_RestPost_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost.class, cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost.Builder.class);
      }

      // Construct using cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        route_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        json_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.internal_static_gazebo_msgs_RestPost_descriptor;
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost getDefaultInstanceForType() {
        return cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost.getDefaultInstance();
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost build() {
        cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost buildPartial() {
        cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost result = new cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.route_ = route_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.json_ = json_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost) {
          return mergeFrom((cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost other) {
        if (other == cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRoute()) {
          bitField0_ |= 0x00000002;
          route_ = other.route_;
          onChanged();
        }
        if (other.hasJson()) {
          bitField0_ |= 0x00000004;
          json_ = other.json_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoute()) {
          
          return false;
        }
        if (!hasJson()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.autolabor.plugin.gazebo.msgs.ProtoRestPost.RestPost) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       *
       * <pre>
       *&#47; &#92;brief ID of this request message
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       *
       * <pre>
       *&#47; &#92;brief ID of this request message
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       *
       * <pre>
       *&#47; &#92;brief ID of this request message
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       *
       * <pre>
       *&#47; &#92;brief ID of this request message
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object route_ = "";
      /**
       * <code>required string route = 2;</code>
       *
       * <pre>
       *&#47; &#92;brief Route to post to.
       * </pre>
       */
      public boolean hasRoute() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string route = 2;</code>
       *
       * <pre>
       *&#47; &#92;brief Route to post to.
       * </pre>
       */
      public java.lang.String getRoute() {
        java.lang.Object ref = route_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            route_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string route = 2;</code>
       *
       * <pre>
       *&#47; &#92;brief Route to post to.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRouteBytes() {
        java.lang.Object ref = route_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          route_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string route = 2;</code>
       *
       * <pre>
       *&#47; &#92;brief Route to post to.
       * </pre>
       */
      public Builder setRoute(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        route_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string route = 2;</code>
       *
       * <pre>
       *&#47; &#92;brief Route to post to.
       * </pre>
       */
      public Builder clearRoute() {
        bitField0_ = (bitField0_ & ~0x00000002);
        route_ = getDefaultInstance().getRoute();
        onChanged();
        return this;
      }
      /**
       * <code>required string route = 2;</code>
       *
       * <pre>
       *&#47; &#92;brief Route to post to.
       * </pre>
       */
      public Builder setRouteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        route_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object json_ = "";
      /**
       * <code>required string json = 3;</code>
       *
       * <pre>
       *&#47; &#92;brief Data to post in JSON format
       * </pre>
       */
      public boolean hasJson() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string json = 3;</code>
       *
       * <pre>
       *&#47; &#92;brief Data to post in JSON format
       * </pre>
       */
      public java.lang.String getJson() {
        java.lang.Object ref = json_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            json_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string json = 3;</code>
       *
       * <pre>
       *&#47; &#92;brief Data to post in JSON format
       * </pre>
       */
      public com.google.protobuf.ByteString
          getJsonBytes() {
        java.lang.Object ref = json_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          json_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string json = 3;</code>
       *
       * <pre>
       *&#47; &#92;brief Data to post in JSON format
       * </pre>
       */
      public Builder setJson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        json_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string json = 3;</code>
       *
       * <pre>
       *&#47; &#92;brief Data to post in JSON format
       * </pre>
       */
      public Builder clearJson() {
        bitField0_ = (bitField0_ & ~0x00000004);
        json_ = getDefaultInstance().getJson();
        onChanged();
        return this;
      }
      /**
       * <code>required string json = 3;</code>
       *
       * <pre>
       *&#47; &#92;brief Data to post in JSON format
       * </pre>
       */
      public Builder setJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        json_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.RestPost)
    }

    static {
      defaultInstance = new RestPost(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.RestPost)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_RestPost_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_RestPost_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017rest_post.proto\022\013gazebo.msgs\"3\n\010RestPo" +
      "st\022\n\n\002id\030\001 \001(\r\022\r\n\005route\030\002 \002(\t\022\014\n\004json\030\003 " +
      "\002(\tB0\n\037cn.autolabor.plugin.gazebo.msgsB\r" +
      "ProtoRestPost"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gazebo_msgs_RestPost_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gazebo_msgs_RestPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gazebo_msgs_RestPost_descriptor,
        new java.lang.String[] { "Id", "Route", "Json", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
