// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: joint_wrench_stamped.proto

package cn.autolabor.plugin.gazebo.gazebomsgs;

public final class ProtoJointWrenchStamped {
  private ProtoJointWrenchStamped() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ForceTorqueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gazebo.msgs.ForceTorque)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    java.util.List<cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench>
        getWrenchList();
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench getWrench(int index);
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    int getWrenchCount();
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    java.util.List<? extends cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder>
        getWrenchOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder getWrenchOrBuilder(
        int index);

    /**
     * <code>required .gazebo.msgs.Time time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required .gazebo.msgs.Time time = 2;</code>
     */
    cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time getTime();
    /**
     * <code>required .gazebo.msgs.Time time = 2;</code>
     */
    cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.TimeOrBuilder getTimeOrBuilder();
  }
  /**
   * Protobuf type {@code gazebo.msgs.ForceTorque}
   */
  public static final class ForceTorque extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:gazebo.msgs.ForceTorque)
      ForceTorqueOrBuilder {
    // Use ForceTorque.newBuilder() to construct.
    private ForceTorque(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ForceTorque(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ForceTorque defaultInstance;
    public static ForceTorque getDefaultInstance() {
      return defaultInstance;
    }

    public ForceTorque getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ForceTorque(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                wrench_ = new java.util.ArrayList<cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench>();
                mutable_bitField0_ |= 0x00000001;
              }
              wrench_.add(input.readMessage(cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = time_.toBuilder();
              }
              time_ = input.readMessage(cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(time_);
                time_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          wrench_ = java.util.Collections.unmodifiableList(wrench_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.internal_static_gazebo_msgs_ForceTorque_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.internal_static_gazebo_msgs_ForceTorque_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque.class, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque.Builder.class);
    }

    public static com.google.protobuf.Parser<ForceTorque> PARSER =
        new com.google.protobuf.AbstractParser<ForceTorque>() {
      public ForceTorque parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ForceTorque(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ForceTorque> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int WRENCH_FIELD_NUMBER = 1;
    private java.util.List<cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench> wrench_;
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    public java.util.List<cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench> getWrenchList() {
      return wrench_;
    }
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    public java.util.List<? extends cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder>
        getWrenchOrBuilderList() {
      return wrench_;
    }
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    public int getWrenchCount() {
      return wrench_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench getWrench(int index) {
      return wrench_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
     */
    public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder getWrenchOrBuilder(
        int index) {
      return wrench_.get(index);
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time time_;
    /**
     * <code>required .gazebo.msgs.Time time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gazebo.msgs.Time time = 2;</code>
     */
    public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time getTime() {
      return time_;
    }
    /**
     * <code>required .gazebo.msgs.Time time = 2;</code>
     */
    public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.TimeOrBuilder getTimeOrBuilder() {
      return time_;
    }

    private void initFields() {
      wrench_ = java.util.Collections.emptyList();
      time_ = cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getWrenchCount(); i++) {
        if (!getWrench(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getTime().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < wrench_.size(); i++) {
        output.writeMessage(1, wrench_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < wrench_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, wrench_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.ForceTorque}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gazebo.msgs.ForceTorque)
        cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorqueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.internal_static_gazebo_msgs_ForceTorque_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.internal_static_gazebo_msgs_ForceTorque_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque.class, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque.Builder.class);
      }

      // Construct using cn.autolabor.plugin.gazebo.msgs.ProtoJointWrenchStamped.ForceTorque.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWrenchFieldBuilder();
          getTimeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (wrenchBuilder_ == null) {
          wrench_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          wrenchBuilder_.clear();
        }
        if (timeBuilder_ == null) {
          time_ = cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.getDefaultInstance();
        } else {
          timeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.internal_static_gazebo_msgs_ForceTorque_descriptor;
      }

      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque getDefaultInstanceForType() {
        return cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque.getDefaultInstance();
      }

      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque build() {
        cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque buildPartial() {
        cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque result = new cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (wrenchBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            wrench_ = java.util.Collections.unmodifiableList(wrench_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.wrench_ = wrench_;
        } else {
          result.wrench_ = wrenchBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (timeBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque) {
          return mergeFrom((cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque other) {
        if (other == cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque.getDefaultInstance()) return this;
        if (wrenchBuilder_ == null) {
          if (!other.wrench_.isEmpty()) {
            if (wrench_.isEmpty()) {
              wrench_ = other.wrench_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWrenchIsMutable();
              wrench_.addAll(other.wrench_);
            }
            onChanged();
          }
        } else {
          if (!other.wrench_.isEmpty()) {
            if (wrenchBuilder_.isEmpty()) {
              wrenchBuilder_.dispose();
              wrenchBuilder_ = null;
              wrench_ = other.wrench_;
              bitField0_ = (bitField0_ & ~0x00000001);
              wrenchBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWrenchFieldBuilder() : null;
            } else {
              wrenchBuilder_.addAllMessages(other.wrench_);
            }
          }
        }
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        for (int i = 0; i < getWrenchCount(); i++) {
          if (!getWrench(i).isInitialized()) {
            
            return false;
          }
        }
        if (!getTime().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrenchStamped.ForceTorque) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench> wrench_ =
        java.util.Collections.emptyList();
      private void ensureWrenchIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          wrench_ = new java.util.ArrayList<cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench>(wrench_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder> wrenchBuilder_;

      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public java.util.List<cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench> getWrenchList() {
        if (wrenchBuilder_ == null) {
          return java.util.Collections.unmodifiableList(wrench_);
        } else {
          return wrenchBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public int getWrenchCount() {
        if (wrenchBuilder_ == null) {
          return wrench_.size();
        } else {
          return wrenchBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench getWrench(int index) {
        if (wrenchBuilder_ == null) {
          return wrench_.get(index);
        } else {
          return wrenchBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder setWrench(
          int index, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench value) {
        if (wrenchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWrenchIsMutable();
          wrench_.set(index, value);
          onChanged();
        } else {
          wrenchBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder setWrench(
          int index, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder builderForValue) {
        if (wrenchBuilder_ == null) {
          ensureWrenchIsMutable();
          wrench_.set(index, builderForValue.build());
          onChanged();
        } else {
          wrenchBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder addWrench(cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench value) {
        if (wrenchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWrenchIsMutable();
          wrench_.add(value);
          onChanged();
        } else {
          wrenchBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder addWrench(
          int index, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench value) {
        if (wrenchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWrenchIsMutable();
          wrench_.add(index, value);
          onChanged();
        } else {
          wrenchBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder addWrench(
          cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder builderForValue) {
        if (wrenchBuilder_ == null) {
          ensureWrenchIsMutable();
          wrench_.add(builderForValue.build());
          onChanged();
        } else {
          wrenchBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder addWrench(
          int index, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder builderForValue) {
        if (wrenchBuilder_ == null) {
          ensureWrenchIsMutable();
          wrench_.add(index, builderForValue.build());
          onChanged();
        } else {
          wrenchBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder addAllWrench(
          java.lang.Iterable<? extends cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench> values) {
        if (wrenchBuilder_ == null) {
          ensureWrenchIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, wrench_);
          onChanged();
        } else {
          wrenchBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder clearWrench() {
        if (wrenchBuilder_ == null) {
          wrench_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          wrenchBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public Builder removeWrench(int index) {
        if (wrenchBuilder_ == null) {
          ensureWrenchIsMutable();
          wrench_.remove(index);
          onChanged();
        } else {
          wrenchBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder getWrenchBuilder(
          int index) {
        return getWrenchFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder getWrenchOrBuilder(
          int index) {
        if (wrenchBuilder_ == null) {
          return wrench_.get(index);  } else {
          return wrenchBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public java.util.List<? extends cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder>
           getWrenchOrBuilderList() {
        if (wrenchBuilder_ != null) {
          return wrenchBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(wrench_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder addWrenchBuilder() {
        return getWrenchFieldBuilder().addBuilder(
            cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder addWrenchBuilder(
          int index) {
        return getWrenchFieldBuilder().addBuilder(
            index, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.JointWrench wrench = 1;</code>
       */
      public java.util.List<cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder>
           getWrenchBuilderList() {
        return getWrenchFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder>
          getWrenchFieldBuilder() {
        if (wrenchBuilder_ == null) {
          wrenchBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrench.Builder, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.JointWrenchOrBuilder>(
                  wrench_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          wrench_ = null;
        }
        return wrenchBuilder_;
      }

      private cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time time_ = cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.TimeOrBuilder> timeBuilder_;
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time getTime() {
        if (timeBuilder_ == null) {
          return time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      public Builder setTime(cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
          onChanged();
        } else {
          timeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      public Builder setTime(
          cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
          onChanged();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      public Builder mergeTime(cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time value) {
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              time_ != cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.getDefaultInstance()) {
            time_ =
              cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.newBuilder(time_).mergeFrom(value).buildPartial();
          } else {
            time_ = value;
          }
          onChanged();
        } else {
          timeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.getDefaultInstance();
          onChanged();
        } else {
          timeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.Builder getTimeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      public cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.TimeOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_;
        }
      }
      /**
       * <code>required .gazebo.msgs.Time time = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.TimeOrBuilder>
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.Time.Builder, cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.TimeOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.ForceTorque)
    }

    static {
      defaultInstance = new ForceTorque(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.ForceTorque)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_ForceTorque_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_ForceTorque_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032joint_wrench_stamped.proto\022\013gazebo.msg" +
      "s\032\022joint_wrench.proto\032\ntime.proto\"X\n\013For" +
      "ceTorque\022(\n\006wrench\030\001 \003(\0132\030.gazebo.msgs.J" +
      "ointWrench\022\037\n\004time\030\002 \002(\0132\021.gazebo.msgs.T" +
      "imeB:\n\037cn.autolabor.plugin.gazebo.msgsB\027" +
      "ProtoJointWrenchStamped"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.getDescriptor(),
          cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.getDescriptor(),
        }, assigner);
    internal_static_gazebo_msgs_ForceTorque_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gazebo_msgs_ForceTorque_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gazebo_msgs_ForceTorque_descriptor,
        new java.lang.String[] { "Wrench", "Time", });
    cn.autolabor.plugin.gazebo.gazebomsgs.ProtoJointWrench.getDescriptor();
    cn.autolabor.plugin.gazebo.gazebomsgs.ProtoTime.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
